# -*- coding: utf-8 -*-
"""결측치 처리하기.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18r8k4cRsUZg0pM6gXWNNdTKHjKeqG_57
"""

import pandas as pd

df = pd.read_csv('/content/scores.csv')

df.isnull().sum()

df.info()

df.dropna()

df.head()

df.dropna(axis=1)

df.head()

df.fillna(0).head()

df.head()

df.fillna(method ='ffill').head()

df.fillna(method ='bfill').head()

df.head()

df.fillna({'kor':80}).head()

df['kor'].mean()