# -*- coding: utf-8 -*-
"""기본 그래프.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/121Pxkd1ahMbOtyjVu-pMtpPm0hYfYlum
"""

import matplotlib.pyplot as plt

x = ['a','b','c','d','e']
y = [1,3,2,10,7]

plt.plot(x,y)

plt.bar(x,y)

plt.barh(x,y)

plt.scatter(x,y)

plt.scatter(x,y,label = 'scater')
plt.bar(x,y,label='bar')
plt.plot(x,y,label='plot')
plt.title('test title')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.show()

import pandas as pd

df = pd.read_csv('/content/scores.csv')

x = df['name']
y = df['kor']
plt.bar(x,y)
plt.xticks(rotation=90)
plt.title('scores',size=20)
plt.xlabel('name',size=15)
plt.ylabel('score',size=15)
plt.show()

