# -*- coding: utf-8 -*-
"""데이터 확인하기.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FaNXJmJE-VoDkhABspW0yiDo-uwvj_jV
"""

import pandas as pd

df = pd.read_csv('/content/scores.csv')

df.head()

df.tail()

df.sample(frac=0.2)

df.nlargest(5, 'eng')

df.nsmallest(5, 'eng')

df.shape

len(df)

df.columns

df.index

df.dtypes

df.info()

df['kor'].unique()

df['kor'].value_counts()

df.describe()

