# -*- coding: utf-8 -*-
"""데이터(추가,삭제,수정).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jSis0ja2aMX7c67XqsBi6GK2iy6hsDVf
"""



import pandas as  pd

df = pd.read_csv('/content/scores.csv')
df.head()

df['no'] = range(1,31)
df.head()

df['sum'] = df['kor'] + df['math'] + df['eng']
df.head()

df['no'] = df['no']+99
df.head()

df.drop(columns=['sum','no'], inplace=True)
df.head()

df.columns = ['이름','국어','영어','수학']
df.head()

df.rename(columns = {'이름':'성명'},inplace=True)
df.head()

