# -*- coding: utf-8 -*-
"""원하는 데이터 추출.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YzLnUlYTNkHQ6qwZuox4zM_YfkUgUkfy
"""

import pandas as pd



import pandas as pd

df = pd.read_csv('/content/scores.csv')

df.head()

df.index = 'i' + df.index.astype('str')

df.head()

df.loc['i3']

df.loc[['i1','i3','i5']]

df.loc[['i3']]

df.loc['i1','kor']

df.loc['i1',['kor','eng']]

df.loc[['i1','i3','i5'],'name']

df.loc[['i1','i3','i5'],['name','kor']]

df.loc[:,'kor']

df.loc[:,['kor']]

df.iloc[0]

df.iloc[[1,3,5]]

df.iloc[[3]]

df.iloc[1:4]

df.iloc[1:6:2]

df.iloc[[-2,-1]]

df.iloc[[1,3,4],1]

df.iloc[[1,3,4],[1,2]]

df.iloc[:,[1,2]]

