# -*- coding: utf-8 -*-
"""자료형 변환.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Em27q2rwH86xsNrkDN6EhMHt2YR9Lgx4
"""

import pandas as pd

df = pd.DataFrame({'float':[1.0,2.0],
                   'int':[1,2],
                   'datetime':[pd.Timestamp('20200101'),pd.Timestamp('20210101')],
                   'string':['a','b'],
                   'bool':[True,False],
                   'object':[1,'-'],
                   'float2':[1.0,2]})

df

df.dtypes

df['int'].dtype

type(df.loc[0,'object'])

type(df.loc[1,'object'])

df = pd.DataFrame({'col':[1,2],'col2':[3,4]})
df

df.dtypes

df = df.astype('float64')

df

df.dtypes

df = df.astype('str')
df.dtypes

df = df.astype('float').astype('int')
df.dtypes

df['col2'] = df['col2'].astype('str')
df.dtypes

df['col2'] = df['col2'].astype('float')
df.dtypes

df['col2'] = df['col2'].astype('int')
df.dtypes

df = pd.DataFrame({'col':[1,2],'col2':[3,4],'col3':[5,'-']})
df

df['col3'] = df['col3'].astype('str')
type(df.loc[0,'col3'])

pd.to_numeric(df['col3'][0],errors='ignore')

df['col3'] = pd.to_datetime(df['col3'],errors='ignore')

df.dtypes

