# -*- coding: utf-8 -*-
"""행 변경하기.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hNqjm-xPesycgd99e3aCnlJpgLMye6Qw
"""

import pandas as pd

df = pd.read_csv('/content/scores.csv')

df.index = range(100,3100,100)
df.head()

df.loc[35] = ['aaa',70,80,90]
df.loc[34] = ['ddd',80,90,100]
df.tail()

df.loc[3000] = ['ccc',60,70,80]
df.tail()

df.drop(index = [3000,35,34],inplace=True)
df.tail()

df.rename(index = {100:'a',200:'b'},inplace = True)
df.head()

df = pd.read_csv('/content/scores.csv')
df.head()
df_copy = df.copy()

df.head()

df_copy.head()

df_copy.math = df.math+5

df_copy.head()

def plus5(x):
  score = x+5
  if score > 100:
    score = 100
  return score

df_copy['math'] = df_copy['math'].apply(plus5).head()

df_copy.head()

def plusn(x,n):
  score = x+n
  if score > 100:
    score = 100
  return score

df_copy['eng'] = df['eng'].apply(plusn, n=1).head()

df_copy.head()

df = pd.read_csv('/content/scores.csv')
df.index = df.name
df.drop(columns = ['name'],inplace = True)

df_copy = df.copy()

df.head()

df_copy.head()

def print_me(x):
  print(x)
df.apply(print_me, axis=1)

def get_sum(x):
  return x.sum()

df_copy['sum'] = df.apply(get_sum, axis=1)

df_copy.head()

df_copy.loc['sum'] = df.apply(get_sum, axis=0)

df.copy

